
- name: stop DKG service
  become: true
  systemd:
    name: dkg.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ dkg_user_home }}/chainspecs/arana_testnet_raw.json"
    dest: "{{ dkg_user_home }}/arana_testnet_raw.json"
    owner: dkg
    mode: '0644'

- name: purge chain
  become: true
  shell: |
    set -o pipefail
    {{ dkg_bin }} purge-chain -y --chain "{{ dkg_user_home }}/arana_testnet_raw.json" --base-path {{ chain_data_dir }}  --database paritydb
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall DKG systemd unit file (authority node)
  template: src=dkg-authority-node.j2 dest=/etc/systemd/system/dkg.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ bootnodes }}"
    authority: "{{ authority }}"
  tags:
    dkg-service

- name: reinstall DKG systemd unit file (full node)
  template: src=dkg-full-node.j2 dest=/etc/systemd/system/dkg.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    dkg-service

- name: start dkg service
  become: true
  systemd:
    name: dkg.service
    state: started
    daemon_reload: yes