
- name: stop DKG service
  when: "'full_node' in group_names"
  become: true
  systemd:
    name: dkg.service
    state: stopped

- name: purge chain
  become: true
  when: "'full_node' in group_names"
  shell: |
    set -o pipefail
    {{ dkg_bin }} purge-chain -y --chain "{{ dkg_user_home }}/arana_testnet_raw.json" --base-path {{ chain_data_dir }}  --database paritydb-experimental
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall DKG systemd unit file (full node)
  template: src=dkg-full-node.j2 dest=/etc/systemd/system/dkg.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    dkg-service

# - name: start dkg service
#   when: "'full_node' in group_names"
#   become: true
#   systemd:
#     name: dkg.service
#     state: started
#     daemon_reload: yes