---
 - name: peek full logs
   hosts: 
      - full_node
   tasks:
      - name: peep full logs
        shell: |
          set -o pipefail
          journalctl -u dkg --no-pager > /root/dkg.log
          tail -n 100 /root/dkg.log
        become: yes
        args:
          executable: /bin/bash
        changed_when: False
        register: command_output

      - name: result
        debug:
          msg: "Command result: {{ command_output.stdout }}"

      - name: remove log
        file:
          path: /root/dkg.log
          state: absent