
- hosts:
    - full_node
    - authority_node
  tasks:
    - name: stop DKG service
      become: true
      systemd:
        name: dkg.service
        state: stopped

    - name: start DKG service
      become: true
      systemd:
        name: dkg.service
        state: started
        daemon_reload: yes
